name: istate
description: "A simple, performant state management solution for Flutter applications."
homepage: https://github.com/IbrahimKhatrii/istate
repository: https://github.com/IbrahimKhatrii/istate
version: 1.0.1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
